### ISSUE TITLE
Display problem onkel nexus 5

### ISSUE THREAD

**Issue by toraschi** [costales/unav#12] opened 2020-03-07 16:37 UTC
Hi 
i've notissed a diplay error on The menu above one need futher information when you make a routiing simulation. See the screeshot 
![screenshot20200306_182527823](https://user-images.githubusercontent.com/32172610/76147224-4d84cb80-609a-11ea-9cc0-cd2eef077590.png)

**Comment by costales** [comment] 2020-03-07 16:45
Hi, 
Thanks for the feeback. The issue is about the size of the 2 icons, isn't it?
Could you tell me the steps for reproduce it?
Thanks in advance and a hug!

**Comment by toraschi** [comment] 2020-03-09 18:17
Hi costales,
yes it's about the Icons. To reproduce it make two decisions and make simulation of the route with the dubble arrow. Then push the button with the roadsign in the blue aria above. Then you see the Icons like that. If you put more options in the near by settings it's ever worse because the Incons are over each other.

**Comment by costales** [comment] 2020-03-10 18:07
Hi! 
Could you confirm me that it is fixed in version 2.7? You have it on the Store.
Thanks in advance!

**Comment by toraschi** [comment] 2020-03-13 16:58
Hi costales the Icons rare displayed correctly now. But Ifound an other display problem . I open a new issue therefore

**Comment by costales** [comment] 2020-09-07 12:28
This should not be appears in uNav 3. If yes, please come back here :) Thanks.

**Closed as completed by costales** 2020-09-07 12:28 UTC
